name: kukoki_flutter
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  email_validator: ^2.1.17
  flutter_native_splash: ^2.2.11
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1
  gender_picker: ^1.1.0
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  lottie: ^1.4.3
  provider: ^6.0.3
  sliding_up_panel: ^2.0.0
  webview_flutter: ^3.0.0
  http: ^0.13.5
  bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/SplashScreenLogo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/lottie/
    - assets/icons/
    - assets/images/payments/
    - assets/images/foods/resep/
    - assets/images/foods/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700



