import 'dart:ui';

class Resep {
  int? menuId;
  String? menuImage;
  String? menuName;
  String? menuPortion;
  String? menuPrice;
  String? menuPreference;
  String? menuDescription;
  String? menuDuration;
  List<String>? menuIngredients;
  List<String>? menuTools;
  String? menuReview;
  List<String>? menuProcedure;

  Resep({
    required this.menuId,
    required this.menuImage,
    required this.menuName,
    required this.menuPortion,
    required this.menuPrice,
    required this.menuDuration,
    required this.menuPreference,
    required this.menuDescription,
    required this.menuIngredients,
    required this.menuTools,
    required this.menuReview,
    required this.menuProcedure,
  });
}

List<Resep> listResep = [
  Resep(
      menuId: 0,
      menuImage: 'assets/images/foods/resep/salmon.png',
      menuName: 'Grilled Salmon',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp40.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '40 min',
      menuDescription:
          'Di samping menjadi salah satu sumber protein yang berkualitas tinggi, ikan salmon juga kaya akan asam lemak omega-3. Asam lemak omega-3 sangat berguna bagi kesehatan jantung, otak, dan organ tubuh lainnya. Selain itu rasanya lezat dan mudah diolah.',
      menuIngredients: [
        '4 potong (@ 200 g) fillet ikan salmon',
        '1 sdt garam',
        '1 sdt merica hitam butiran, gerus kasar',
        '1 sdt merica hitam butiran, gerus kasar',
        '2 sdm minyak zaitun',
        '2 sdm mentega',
        '4 siung bawang putih, iris tips',
        '4 sdm air jeruk lemon'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur'],
      menuReview: '4,8',
      menuProcedure: ['1. Cuci Semua Sayur', '']),
  Resep(
      menuId: 1,
      menuImage: 'assets/images/foods/resep/dagingsayur1.png',
      menuName: 'Tumis Daging dan Sayur',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp36.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '42 min',
      menuDescription:
          'Ingin membuat menu makan dengan bahan daging sapi? Tumis sayur daging sapi ini mungkin bisa dicoba untuk menu hidangan makan bersama keluarga.',
      menuIngredients: [
        '1/2 kg daging sapi',
        '1 ikat sawi',
        '2 buah wortel',
        '1/4 bagian kubis',
        '1/4 bagian brokoli',
        '1/4 bagian kol',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur'],
      menuReview: '4,1',
      menuProcedure: [
        '1. Cuci bersih daging, dan rebus hingga empuk.',
        '2. Jika daging sudah matang, potong daging sesuai selera. Jangan terlalu tebal ataupun telalu tipis.',
        '3. Kupas, wortel dan potong melingkar. Potong-potong pula kubis dan sawi sesuai selera.',
        '4. Potong tipis bawang merah, bawang putih, cabai.',
        '5. Tumis semua bumbu dengan minyak secukupnya, gunakan api sedang.',
        '6. Jika bumbu sudah beraroma masukkan 300 ml air, daging, dan sayuran. Biarkan kuah meresap ke dalam daging.',
        '7. Bila sudah matang, matikan kompor dan sajikan tumis sayur daging sapi.'
      ]),
  Resep(
      menuId: 2,
      menuImage: 'assets/images/foods/resep/dagingsayur2.png',
      menuName: 'Teriyaki',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp38.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Hidangan ini terbuat dari daging yang direndam dengan saus teriyaki, kecap asin, kecap manis, dan bahan-bahan lainnya. Saus teriyaki memiliki cita rasa yang lezat, perpaduan rasa asin dan manis. Di Jepang, saus teriyaki sendiri sebenarnya mengandung sake.',
      menuIngredients: [
        'Iris tipis daging sapi 200 gram',
        'Biji wijen disangrai 2 sdm ',
        'Bawang bombay iris 1/2 butir',
        'Daun bawang, iris halus - 1 batang',
        'Margarin / mentega - 2 sdm',
        'Bawang putih, parut - 2 siung',
        'Saus teriyaki - 2 sdm',
        'Kecap asin - 1 sdm',
        'Kecap manis - 1 sdm',
        'Saus tiram - 1 sdm',
        'Lada hitam - 1 sdt',
        'Gula - 1 sdt',
        'Kaldu bubuk - 1 sdt',
        'Garam - 1/2 sdt',
        'Saus tomat - 1 sdt',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci', 'Sendok'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Campur rata semua bahan bumbu rendaman.',
        '2. Masukkan daging dalam bumbu rendaman, aduk hingga merata. Diamkan dalam kulkas selama 1 malam. Sisihkan.',
        '3. Panaskan margarin. Tumis bawang bombay hingga wangi.',
        '4. Masukkan daging sambil diaduk-aduk cepat hingga berubah warna. Angkat.',
        '5. Taburi daging dengan biji wijen dan daun bawang.',
        '6. Siap disajikan.',
      ]),
  Resep(
      menuId: 3,
      menuImage: 'assets/images/foods/resep/dagingsayur3.png',
      menuName: 'Lapis Daging Sapi',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp46.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '50 min',
      menuDescription:
          'Daging lapis adalah sajian makanan yang diadaptasi dari kuliner Belanda manis dan gurih. Hidangan ini sangat cocok disantap dengan nasi hangat sebagai menu harian, baik makan siang atau makan malam. Bagi Anda pecinta olahan daging, tentu menu lezat yang satu ini wajib Anda coba.',
      menuIngredients: [
        'Iris tipis daging sapi 200 gram',
        'Biji wijen disangrai 2 sdm ',
        'Bawang bombay iris 1/2 butir',
        'Daun bawang, iris halus - 1 batang',
        'Margarin / mentega - 2 sdm',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,9',
      menuProcedure: [
        '1. Iris pipih daging dengan memotong serat.',
        '2. Campur bumbu halus dan daging menjadi satu.',
        '3. Panaskan minyak sedikit, tumis daging sampai berubah warna, tambahkan air.',
        '4. Masukkan bumbu lengkuas, batang serai, daun jeruk, kayu manis, telur dan kecap.',
        '5. Masak sampai daging empuk, agar daging lebih empuk dan bumbu meresap.',
        '6. Tunggu sampai air berkurang. Tambahkan gula dan garam.',
        '7. Koreksi rasa, matikan api. Siap disajikan.',
      ]),
  Resep(
      menuId: 4,
      menuImage: 'assets/images/foods/resep/dagingsayur4.png',
      menuName: 'Daging Sapi Asam Manis',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '35 min',
      menuDescription:
          'Ketika persediaan daging kurban melimpah, ada banyak cara membuatnya menjadi masakan spesial di Hari Raya Idul Adha. Satu di antara resep yang direkomendasikan yaitu membuatnya menjadi masakan daging sapi asam manis.',
      menuIngredients: [
        '500 gram daging sapibagian sengkel potong-potong',
        '500 ml santan kental dicampur dengan air 1 liter',
        '3 keping gula merah',
        '10 ml air asam jawa',
        '1 sdt bumbu kaldu jamur',
        '2 batang serai',
        '5 lembar daun salam',
        '3 ruas jari lengkuas, geprek',
        '3 butir kemiri',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Haluskan bawang merah, bawang putih, kemiri, dan ketumbar.',
        '2. Rebus santan sampai mendidih dan masukkan bumbu halus, daging, parutan gula merah, air asam jawa, kaldu jamur, dan aduk rata. Masukkan serai, daun salam, dan lengkuas.',
        '3. Masak terus dalam api kecil sambil diaduk perlahan, masak terus sampai cairan menyusut, koreksi rasa.',
        '4. Beri taburan bawang goreng, nikmati selagi hangat.',
      ]),
  Resep(
      menuId: 5,
      menuImage: 'assets/images/foods/resep/dagingsayur5.png',
      menuName: 'Bistik Sapi',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp42.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '40 min',
      menuDescription:
          'Olahan daging sapi saus asam manis sepertinya sudah terdengar biasa, tapi beda halnya bila disajikan di dalam kelapa muda. My Thai, restoran masakan Thailand di Bogor, menyajikan daging sapi saus asam manis di dalam batok kelapa. Olahan tersebut dinamakan Sapi dalam Kelapa.',
      menuIngredients: [
        '5 siung bawang putih',
        '1/2 sdt lada bubuk',
        '500 gram daging sapibagian sengkel potong-potong',
        '500 ml santan kental dicampur dengan air 1 liter',
        '3 keping gula merah',
        '10 ml air asam jawa',
        '1 sdt bumbu kaldu jamur',
        '2 batang serai',
        '5 lembar daun salam',
        '3 ruas jari lengkuas, geprek',
        '3 butir kemiri',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Rebus daging masak agak empuk. Sisihkan air kaldunya, kemudian potong-potong daging sesuai selera.',
        '2. Tumis bawang bombai, kemudian masukkan bumbu halus. Masak hingga tanak.',
        '3. Masukkan potongan daging, aduk. Tambahkan kecap manis, saus tiram, kecap asin, saus tomat dan aduk rata.',
        '4. Masukkan air kaldu masak hingga air mengental dan daging empuk.',
        '5. Hidangkan.',
      ]),
  //Sayur
  Resep(
      menuId: 6,
      menuImage: 'assets/images/foods/resep/sayur0.png',
      menuName: 'Sayur Bobor Bayam',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Sayur bayam selalu identik dengan sayur bening. Namun, jika kamu bosan dengan sayur bening, bayam bisa diolah jadi bobor bayam, lho.',
      menuIngredients: [
        '2 ikat bayam (siangi)',
        '500 ml santan cair ',
        '400 ml santan kental',
        '100 gram kecambah kedelai',
        'Garam secukupnya',
        'Gula secukupnya',
        '5 siung bawang putih',
        '2 siung bawang merah',
        'Merica secukupnya'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Siapkan sayur bayam yang sudah disiangi. Cuci lalu tiriskan. Begitu juga dengan kecambah kedelai.',
        '2. Panaskan wajan, tumis bawang putih dan bawang merah hingga aromanya harum. Jika sudah, tambahkan santan cair. Masak hingga hangat mendekati mendidih.',
        '3. Masukkan semua bumbu halus dan garam.',
        '4. Masukkan sayur bayam dan tunggu hingga agak layu. Tambahkan kecambah dan aduk hingga rata. Masak hingga semua bahan empuk dan mendidih.',
        '5. Tambahkan santan kental dan aduk hingga rata. Tambahkan gula dan penyedap rasa agar sayur bobor makin lezat serta nikmat.',
        '6. Biarkan hingga mendidih lalu angkat dan sajikan selagi hangat.',
      ]),
  Resep(
      menuId: 7,
      menuImage: 'assets/images/foods/resep/sayur1.png',
      menuName: 'Tumis Kankung',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '3 siung bawang putih, iris tipis',
        '2 siung bawang merah, iris tipis',
        '5 buah cabai rawit, iris serong',
        '3 buah cabai keriting, iris serong',
        'Garam secukupnya',
        'Gula secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Siapkan semua bahan, panaskan minyak goreng. ',
        '2. Tumis bawang putih dan bawang merah hingga harum.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Tambahkan garam, penyedap dan kaldu jamur bubuk. Aduk rata. ',
        '6. Tambahkan air panas sedikit saja, aduk rata.',
        '7. Koreksi rasa dan angkat tumis kangkung yang telah matang. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 8,
      menuImage: 'assets/images/foods/resep/sayur2.png',
      menuName: 'Bening Kacang Panjang',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp24.000',
      menuPreference: 'Sayur',
      menuDuration: '30 min',
      menuDescription:
          'Resep Sayur bening kacang panjang mudah dan praktis. Buat kalian yang gak mau ribet dengan dunia permasakan.',
      menuIngredients: [
        '10 buah kacang panjang (potong panjang kira-kira 4 cm)',
        '50 gram kecambah kedelai (siangi)',
        '1 buah jagung muda (potong-potong sesuai selera)',
        '5 lembar daun kemangi',
        '3 cm rempah kunci (memarkan)',
        '5 siung bawang merah (iris tipis)',
        '3 siung bawang putih (memarkan)',
        'Gula pasir (secukupnya)',
        'Garam (secukupnya)',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Panaskan minyak (kira-kira 1 sdm) di wajan. ',
        '2. Tumis bawang merah dan bawang putih hingga aromanya harum. ',
        '3. Tambahkan air sesuai selera dan  masukkan kacang panjang serta kecambah kedelai.',
        '4. Masukkan pula garam, rempah kunci, daun kemangi dan jagung muda.',
        '5. Masak hingga semua bahan matang dan empuk. Tambahkan gula dan kaldu ayam bubuk agar rasa sayur bening makin gurih. ',
        '6. Jangan lupa untuk memasukkan buah tomat agar sayur bening ini makin segar.',
        '7. Masak hingga semua bahan masakan matang dan mendidih. ',
        '8. Jika sudah matang, angkat lalu sajikan.',
      ]),
  Resep(
      menuId: 9,
      menuImage: 'assets/images/foods/resep/sayur3.png',
      menuName: 'Sayur Urap',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '1 ikat kangkung',
        '1 ikat kacang panjang',
        '1 buah wortel',
        '1 genggam kecambah',
        '3 buah cabai merah',
        '3 buah cabai rawit',
        '1 ruas kencur',
        '1 cm terasi',
        '3 lembar daun jeruk',
        '2 siung bawang putih',
        '200 gr kelapa parut',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Haluskan bumbu kelapa parut, campur dengan kelapa parut hingga rata. Bungkus dengan daun pisang. Kukus hingga matang atau kurang lebih 20 menit. ',
        '2. Potong-potong sayur dan rebus hingga matang, sisihkan.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sayur kangkung ke dalam wajan, aduk rata dan masak dengan api besar sambil terus diaduk. ',
        '5. Campur kelapa parut bumbu dengan sayuran yang sudah direbus. ',
        '6. Sayur urap-urap siap dinikmati dengan ikan asin dan nasi hangat.',
        '7. Sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 10,
      menuImage: 'assets/images/foods/resep/sayur4.png',
      menuName: 'Tumis Sawi Putih',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp26.000',
      menuPreference: 'Sayur',
      menuDuration: '20 min',
      menuDescription:
          'Sawi putih mengandung vitamin C yang bermanfaat untuk meningkatkan imunitas tubuh dan mencegah kerusakan sel akibat radikal bebas. Oleh karena itu, mengonsumsi sawi putih secara rutin dan teratur dapat membuat Anda tidak mudah terserang penyakit.',
      menuIngredients: [
        '1 bungkul sawi putih, potong-potong sesuai selera',
        '1/2 sdt lada bubuk',
        '5 buah cabai rawit, iris serong',
        '2 siung bawang putih, cingcang halus',
        '3 siung bawang merah, cincang halus',
        'Garam, secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Cuci bersih sayur sawi putih.',
        '2. Panaskan sedikit minyak, tumis bawang putih dan bawang merah hingga harum.',
        '3. Masukkan cabai rawit dan cabai keriting ke dalam tumisan bawang, aduk rata. Tumis hingga semua bumbu layu. ',
        '4. Masukkan sawi ke dalam wajan, aduk rata dan masak hingga layu.',
        '5. Koreksi rasa, masak kembali hingga sayur sawi matang.',
        '6. Angkat, kemudian sajikan selagi masih hangat.',
      ]),
  Resep(
      menuId: 11,
      menuImage: 'assets/images/foods/resep/sayur5.png',
      menuName: 'Terong Balado',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp18.000',
      menuPreference: 'Sayur',
      menuDuration: '15 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '3 buah terong ungu',
        '2 siung bawang merah, iris tipis',
        '5 buah cabai rawit, iris serong',
        '3 buah cabai keriting, iris serong',
        'Garam secukupnya',
        'Gula secukupnya',
        'Kaldu jamur bubuk, secukupnya',
        'Penyedap masakan, secukupnya',
        'Merica secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Potong terong memanjang sesuai selera.',
        '2. Haluskan semua bumbu dengan cara diulek kasar atau diblender hingga halus.',
        '3. Panaskan sedikit minyak, tumis bumbu halus hingga harum.',
        '4. MMasukkan terong ke dalam bumbu, aduk rata dan masak hingga layu serta matang.',
        '5. Tambahkan garam, penyedap dan kaldu jamur bubuk. Aduk rata. ',
        '6. Koreksi rasa, angkat terong balado yang telah matang.',
      ]),
  //Produk Susu
  // Resep(
  //     menuId: 12,
  //     menuImage: 'assets/images/foods/resep/produksusu0.png',
  //     menuName: 'Soto Betawi Susu',
  //     menuPortion: '2 Porsi',
  //     menuPrice: 'Rp32.000',
  //     menuPreference: 'Produk Susu',
  //     menuDuration: '22 min',
  //     menuDescription:
  //         'Soto Betawi merupakan salah satu jenis soto khas Nusantara yang paling digemari. Berkuah putih dan cukup kental, soto Betawi ada yang terbuat dari santan kelapa atau susu. Tak ayal, menu ini identik dengan rasa gurih.',
  //     menuIngredients: [
  //       '1 kg daging sapi (bagian has dan sengkel)',
  //       '3 cm lengkuas digeprek',
  //       '1 batang kayu manis (5 cm)',
  //       '4 lembar daun salam',
  //       '6 butir cengkeh',
  //       '2 batang serai digeprek',
  //       '1500 ml santan',
  //       '500 ml susu cair',
  //       'Minyak untuk menumis bumbu',
  //     ],
  //     menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
  //     menuReview: '4,6',
  //     menuProcedure: [
  //       '1. Rebus sebentar daging yang sudah dipotong, buang air darahnya. Rebus kembali daging sapi dengan 1500 ml santan.',
  //       '2. Tumis bumbu halus bersama lengkuas, daun salam, kayu manis, cengkeh, serai sampai harum. Masukkan bumbu tumis ke dalam rebusan daging. Didihkan, masak sambil diaduk agar santan tidak pecah.',
  //       '3. Masukkan susu. Aduk. Beri garam, gula secukupnya. Cicipi. Masak sampai bumbu meresap dan daging empuk',
  //       '4. Sajikan bersama bahan pelengkap.',
  //     ]),
  // Resep(
  //     menuId: 13,
  //     menuImage: 'assets/images/foods/resep/produksusu1.png',
  //     menuName: 'Spaghetti Brulee',
  //     menuPortion: '2 Porsi',
  //     menuPrice: 'Rp32.000',
  //     menuPreference: 'Produk Susu',
  //     menuDuration: '15 min',
  //     menuDescription:
  //         'Spanghetti panggang brulee adalah campuran resep spaghetti bolognese dan saus bechamel yang dipanggang menjadi hidangan pasta nan creamy.',
  //     menuIngredients: [
  //       '100 gr macaroni',
  //       '300 ml susu cair',
  //       '1 sdm mentega',
  //       '1 sdm terigu',
  //       'Garam',
  //       'Merica bubuk',
  //       'Parutan keju sesuai selera',
  //     ],
  //     menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
  //     menuReview: '4,6',
  //     menuProcedure: [
  //       '1. Pasta: rebus pasta hingga al dente. Tumis bawang bombay dan sosis hingga berubah warna, masukkan saus bolognese, aduk rata. Masukkan pasta yang sudah direbus kedalam saus, aduk rata sisihkan.',
  //       '2. Saus bechamel: tumis bawang putih, masukkan tepung terigu aduk-aduk. Masukkan susu cair, keju, kaldu bubuk dan merica. Masak hingga mendidih dan kental, sisihkan.',
  //       '3. Penyelesaian: tata spaghetti bolognese di dalam wadah tahan panas. Siram dengan saus bechamel.',
  //       '4. Tata potongan keju quickmelt di atasnya. Panggang selama 10 menit dengan suhu 180 derajat.',
  //       '5. Sajikan.',
  //     ]),
  Resep(
      menuId: 14,
      menuImage: 'assets/images/foods/resep/produksusu2.png',
      menuName: 'Pancake Pizza',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp32.000',
      menuPreference: 'Produk Susu',
      menuDuration: '15 min',
      menuDescription:
          'Pizza ini dibuat dengan adonan pancake yang unik. Karena dibuat dengan teflon atau pan dadar, maka tekstur pizza akan menjadi lebih renyah.',
      menuIngredients: [
        '360 ml susu fresh milk',
        '30 ml minyak untuk memasak',
        '2 butir telur',
        '250 ml tepung terigu',
        'Gula secukupnya',
        'Garam secukupnya',
        '2 batang sosis, potong dan tumis sampai agak kecokelatan ',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Untuk membuat adonan pancake, campurkan tepung terigu, garam dan gula. Aduk hingga tercampur.',
        '2. Di mangkuk lain, campurkan susu, telur dan minyak masak. Tuang adonan kering tepung ke dalam adonan susu. Aduk hingga tidak ada gumpalan.',
        '3. Panaskan wajan dengan api kecil, beri minyak (jangan terlalu banyak).',
        '4. Tuang adonan pancake ke dalam wajan sebanyak 3-4 sendok kuah.',
        '5. Tutup wajan sampai permukaan pancake kering. Buka tutup wajan.',
        '6. Oleskan saus tomat hingga rata. Susun mozzarella cheese, tomat, sosis dan sayuran',
        '7. Tutup kembali wajan, tunggu sampai keju mozzarella meleleh.',
        '8. Siap disajikan.',
      ]),
  Resep(
      menuId: 15,
      menuImage: 'assets/images/foods/resep/produksusu3.png',
      menuName: 'Pie Susu Renyah',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Produk Susu',
      menuDuration: '25 min',
      menuDescription:
          'Kulit kue yang gurih renyah dan isi kue yang lembut manis membuat pie susu menjadi oleh-oleh favorit bagi pelanggan Anda.',
      menuIngredients: [
        '175 gr tepung protein sedang',
        '1 sdm gula halus',
        '100 gr margarin atau butter (bisa pakai keduanya)',
        '1 butir kuning telur',
        '100 ml susu cair full cream',
        '85 gr krimer kental manis (susu kental manis)',
        '2 butir kuning telur',
        '1/2 sdt pasta vanilla',
        '1/4 sdt garam',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Kulit: campur semua bahan jadi satu, uleni hingga berbutir-butir. Satukan hingga tercampur rata, kepal-kepal dan cetak pada loyang pie yang sudah diolesi dengan mentega.',
        '2. Tusuk-tusuk bagian tengahnya dengan garpu. Sisihkan.',
        '3. Filling: aduk semua bahan jadi satu dengan whisk sampai tercampur rata, saring.',
        '4. Tuang filling pada kulit pie, panggang dalam oven suhu 160 derajat celcius dengan api atas bawah sampai matang kecokelatan.',
      ]),
  Resep(
      menuId: 16,
      menuImage: 'assets/images/foods/resep/produksusu4.png',
      menuName: 'Cream Soup',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp32.000',
      menuPreference: 'Produk Susu',
      menuDuration: '15 min',
      menuDescription:
          'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
      menuIngredients: [
        '100 gr daging ayam',
        '1 buah wortel',
        '1 buah jagung manis',
        '1 helai bawang prei',
        '1 buah bawang bombay',
        '200 ml susu full cream bubuk atau cair',
        '3 sdm tepung maizena',
        '4 siung bawang putih',
        '1 sdt lada bubuk',
        '1 sdt kaldu ayam bubuk',
        '2 sdm garam',
        'Mentega secukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Cuci ayam dan iris dadu kecil, iris wortel dan siapkan jagung yang sudah dipipil, kemudian bawang prei diiris tipis.',
        '2. Rebus ayam beserta tulangnya dalam 1 liter air. Selagi menunggu, tumis irisan bawang putih dan bawang bombay sampai harum. Masukkan tumisan ke dalam rebusan ayam yang telah mengeluarkan kaldunya.',
        '3. Masukkan semua bahan sayuran ke dalam rebusan, aduk terus hingga sayuran empuk. Masukkan perlahan susu full cream dan aduk hingga merata. Setelah semua bahan empuk, masukkan garam dan lada.',
        '4. Larutkan tepung maizena dengan air secukupnya, setelah larut, masukkan ke dalam rebusan dan aduk hingga merata. Ketika sup dirasa sudah mengental matikan api dan siap dihidangkan.',
      ]),
  Resep(
      menuId: 17,
      menuImage: 'assets/images/foods/resep/produksusu5.png',
      menuName: 'Mushroom Zuppa Soup',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp28.000',
      menuPreference: 'Produk Susu',
      menuDuration: '25 min',
      menuDescription:
          ' Kalau kamu ingin coba kreasi kuliner ini, yuk, coba bikin mushroom zuppa soup yang gak kalah nikmat lewat resepnya di bawah ini.',
      menuIngredients: [
        '300 gr jamur kancing, iris',
        '2 bawang putih, geprek, cincang kecil-kecil',
        '1 bawang bombay, cincang',
        '800 ml air dan 1,5 sdm kaldu bubuk',
        '200 ml susu cair',
        '3 sdm tepung terigu',
        '3 sdm butter atau margarin',
        '1 sdm margarin dan 1 sdm minyak untuk menumis',
        'Garam, gula, dan lada scukupnya',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Tumis bawang putih dan bombay dengan 1 sdm margarin atau butter dan 1 sdm minyak.',
        '2. Masukkan jamur, aduk rata, beri 1 sdt garam dan lada, terus aduk sampai warnanya kecokelatan.',
        '3. Masukkan 3 sdm margarin atau butter.',
        '4. Masukkan 3 sdm tepung terigu, aduk cepat supaya tidak menggumpal.',
        '5. Masukkan 800 ml air secara perlahan sambil diaduk supaya tidak menggumpal.',
        '6. Saat mulai kental masukkan susu cair.',
        '7. Aduk rata sampai mengental, cek rasa, bisa ditambah garam, gula, dan lada sesuai selera.',
      ]),
  //Cepat dan Mudah
  Resep(
      menuId: 18,
      menuImage: 'assets/images/foods/resep/cepatdanmudah0.png',
      menuName: 'Sop Sayur Makaroni',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp16.000',
      menuPreference: 'Cepat dan Mudah',
      menuDuration: '15 min',
      menuDescription:
          'Sop Sayur Makaroni cocok untuk anda yang sedang buru-buru ataupun sibuk karena proses memasaknya sangatlah mudah!',
      menuIngredients: [
        '2 buah Wortel',
        '2 buah Kentang',
        'Kol, buncis secukupnya',
        'Makaroni secukupnya',
        '2 biji daun bawang',
        '¼ butir tomat',
        '3 siung bawang putih',
        '¼ sdt merica',
        'Pala bubuk seujung kecil sendok teh',
        '½ sdt gula pasir',
        '1 sdt garam',
        '1/4 sdt Royco rasa sapi',
        '800 ml air'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Cuci bersih semua sayur kemudian potong-potong wortel, kentang, kol, buncis, tomat dan daun bawang.',
        '2. Haluskan bawang putih, garam dan merica.',
        '3. Panaskan margarine tumis bawang putih dan daun bawang hingga harum, tuang air dan masukkan makaroni dan kentang.',
        '4. Jika makaroni sudah ½ matang, masukkan sayur.',
        '5. Setelah dirasa semua sayur matang masukkan gula dan penyedap makanan, angkat.',
      ]),
  Resep(
      menuId: 19,
      menuImage: 'assets/images/foods/resep/cepatdanmudah1.png',
      menuName: 'Cap Cay Goreng',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp13.000',
      menuPreference: 'Cepat dan Mudah',
      menuDuration: '15 min',
      menuDescription:
          'Makanan yang sangat terkenal ini mudah dimasak lho, yuk coba masak Cap Cay goreng!',
      menuIngredients: [
        '1 buah Wortel',
        '1 buah sawi putih',
        'Kol dan sawi hijau secukupnya',
        '2 biji daun bawang',
        '1 buah bawang bombay',
        '1 piring kecil udang',
        '1 piring kecil daging ayam',
        '3 butir bakso jadi',
        '2 biji daun bawang',
        '3 siung bawang putih',
        '¼ sdt merica',
        'Pala bubuk seujung kecil sendok teh',
        '½ sdt gula pasir',
        '1 sdt garam',
        '1/4 sdt Royco rasa sapi',
        '800 ml air'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,4',
      menuProcedure: [
        '1. Campur maizena dengan ¼ gelas air, aduk rata, sisihkan.',
        '2. Cuci bersih semua sayur kemudian potong-potong wortel, sawi putih, sawi hijau dan kol.',
        '3. Iris tipis-tipis tomat, daun bawang dan bawang bombay.',
        '4. Potong-potong udang, bakso dan daging ayam.',
        '5. Haluskan bawang putih, garam, dan pala bubuk.',
        '6. Panaskan minyak, tumis bawang bombay, bawang putih halus, daun bawang, udang ayam hingga harum, tuang air dan masukkan semua sayur dan bakso.',
        '7 Setelah dirasa semua sayur dan daging matang masukkan maizena cair, lalu masukkan gula dan penyedap. Aduk-aduk hingga kuah bersisa sedikit. Angkat.',
      ]),
  Resep(
      menuId: 20,
      menuImage: 'assets/images/foods/resep/cepatdanmudah2.png',
      menuName: 'Sup Ayam Jagung',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp18.000',
      menuPreference: 'Cepat dan Mudah',
      menuDuration: '15 min',
      menuDescription:
          'Sering disajikan dan banyak peminatnya, yuk kita cari tahu bagaimana cara masak sup ayam jagung!',
      menuIngredients: [
        '2 buah jagung manis, serut biji jagungnya',
        '1 piring kecil daging ayam',
        '1 butir telur, kocok lepas',
        '2 Biji daun bawang',
        '1 buah bawang bombay',
        '3 siung bawang putih',
        '1/4 sdt merica',
        '1/2 sdt gula pasir',
        '1 sdt garam',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,8',
      menuProcedure: [
        '1. Campur maizena dengan ¼ gelas air, aduk rata sisihkan.',
        '2. Haluskan ayam dan jagung dengan food processor.',
        '3. Iris halus bawang bombay dan daun bawang. Haluskan bawang putih, garam, dan pala bubuk.',
        '4. Panaskan minyak, tumis bawang bombay, bawang putih halus dan daun bawang hingga harum.',
        '5. Masukkan ayam dan jagung, tuang air.',
        '6. Setelah dirasa semua matang dan empuk, tuang telur kocok, aduk-aduk. Kemudian masukkan maizena cair, gula, oregano dan penyedap.',
        '7. Aduk-aduk hingga mengental. Angkat.'
      ]),
  // Resep(
  //     menuId: 21,
  //     menuImage: 'assets/images/foods/resep/cepatdanmudah3.png',
  //     menuName: 'Sop Sayur Makaroni',
  //     menuPortion: '2 Porsi',
  //     menuPrice: 'Rp14.000',
  //     menuPreference: 'Cepat dan Mudah',
  //     menuDuration: '15 min',
  //     menuDescription:
  //         'Kangkung tumis atau kadang disebut tumis kangkung atau cah kangkung adalah hidangan sayur tumis yang lazim ditemukan dalam hidangan Asia.',
  //     menuIngredients: [
  //       '2 buah Wortel',
  //       '2 buah Kentang',
  //       'Kol, buncis secukupnya',
  //       'Makaroni secukupnya',
  //       '2 biji daun bawang',
  //       '¼ butir tomat',
  //       '3 siung bawang putih',
  //       '¼ sdt merica',
  //       'Pala bubuk seujung kecil sendok teh',
  //       '½ sdt gula pasir',
  //       '1 sdt garam',
  //       '1/4 sdt Royco rasa sapi',
  //       '800 ml air'
  //     ],
  //     menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
  //     menuReview: '4,6',
  //     menuProcedure: [
  //       '1. Cuci bersih semua sayur kemudian potong-potong wortel, kentang, kol, buncis, tomat dan daun bawang.',
  //       '2. Haluskan bawang putih, garam dan merica.',
  //       '3. Panaskan margarine tumis bawang putih dan daun bawang hingga harum, tuang air dan masukkan makaroni dan kentang.',
  //       '4. Jika makaroni sudah ½ matang, masukkan sayur.',
  //       '5. Setelah dirasa semua sayur matang masukkan gula dan penyedap makanan, angkat.',
  //     ]),
  Resep(
      menuId: 22,
      menuImage: 'assets/images/foods/resep/cepatdanmudah4.png',
      menuName: 'Tahu Telor',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp16.000',
      menuPreference: 'Cepat dan Mudah',
      menuDuration: '15 min',
      menuDescription:
          'Hayo, siapa yang enggak tahu Tahu Telor. Enak, murah, mudah, yuk kita belajar cara masak tahu telor!',
      menuIngredients: [
        '3 potong tahu kotak putih, potong–potong 1x1x1/2 cm',
        '4 butir telur',
        '½ sdt garam',
        '¼ sdt merica bubuk',
        '1 siung bawang putih, haluskan',
        'Sambal Kacang Kecap',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,9',
      menuProcedure: [
        '1. Kocok telur dengan semua bumbu hingga merata.',
        '2. Masukkan tahu, aduk hati-hati agar tahu tidak hancur.',
        '3. Bagi 2 adonan (agar tidak susah membaliknya).',
        '4. Goreng ½ adonan dengan sedikit minyak dalam api kecil dan wajan anti lengket.',
        '5. Tunggu hingga 1 sisi matang kecoklatan, baru dibalik. Tunggu matang sisi berikutnya, angkat. Goreng ½ adonan sisanya.',
        '6. Untuk sambal kacang kecap :Campur bumbu sambal pecel dengan air panas, aduk hingga rata. Tuangkan kecap. Siramkan keatas tahu telur.',
      ]),
  Resep(
      menuId: 23,
      menuImage: 'assets/images/foods/resep/cepatdanmudah5.png',
      menuName: 'Ayam Kare',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp21.000',
      menuPreference: 'Cepat dan Mudah',
      menuDuration: '15 min',
      menuDescription:
          'Lezat, enak, dan kental, ayam kare dapat menjadi pilihan belajar masak anda!',
      menuIngredients: [
        '½ ekor ayam, potong–potong sesuai selera',
        '2 buah Wortel',
        '2 buah Kentang',
        'Kol, buncis secukupnya',
        'Makaroni secukupnya',
        '2 biji daun bawang',
        '¼ butir tomat',
        '3 siung bawang putih',
        '¼ sdt merica',
        'Pala bubuk seujung kecil sendok teh',
        '½ sdt gula pasir',
        '1 sdt garam',
        '1 kotak santan kara',
        '800 ml air'
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Cuci bersih daging ayam.',
        '2. Haluskan semua bumbu, kecuali lengkuas, daun serai dan daun salam.',
        '3. Panaskan minyak, tumis semua bumbu, masukkan ayam. Tuang air dan tunggu hingga ayam empuk.',
        '4. Setelah itu masukkan santan, gula, garam dan penyedap. Angkat. Taburi bawang goreng.',
      ]),
  Resep(
      menuId: 24,
      menuImage: 'assets/images/foods/resep/roti0.jpg',
      menuName: 'Roti Gandum Vegan Oat',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Roti',
      menuDuration: '12 min',
      menuDescription:
          'Resep Roi Gandum Vegan Oat. Buat kalian yang hobi makan roti tanpa ribet .',
      menuIngredients: [
        '200 gr terigu protein tinggi',
        '100 gr tepung gandum',
        '100 gr oat instan',
        '15 gr ragi instan',
        '75 gr gula pasir',
        '275 gr air hangat',
        '1/2 sdt garam',
        '50 ml olive oil / boleh ganti minyak goreng sepunya nya',
        '100 gr cranberry, rendam dengan air dingin, tiriskan',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Gelas ukur', 'Panci'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Campur tepung terigu, tepung gandum, oat, ragi instan dan gula pasir. Aduk rata.',
        '2. Tuang air hangat sedikit demi sedikit dan aduk sampai kalis. ',
        '3. Tambahkan olive oil dan garam. Uleni sampai elastis. Jangan khawatir apabila adonan agak lengket atau lembek.',
        '4. Masukkan cranberry, aduk menyebar hingga rata, bulatkan, diamkan 30 menit.',
        '5. Kempiskan adonan, rolling dan gulung lipat sesuai dengan loyang masing masing. ',
        '6. Diamkan kembali selama 60 menit (fermentasi ke 2) atau sampai ukuran 2 kali lipat.',
        '7. Oles susu full cream, oven pada suhu 180 derajat selama kurang lebih 45 menit. Keluarkan dan sajikan. ',
      ]),
  Resep(
      menuId: 25,
      menuImage: 'assets/images/foods/resep/roti1.jpg',
      menuName: 'Sandwich Roti Gandum Avocado',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Roti',
      menuDuration: '14 min',
      menuDescription:
          'Resep Roti Gandum Avocado yang membuat hari anda semakin cerah. Tanpa memerlukan waktu yang lama anda sudah dapat membuat roti yang nikmat!! .',
      menuIngredients: [
        '4 lembar roti gandum',
        '2 lembar daun selada',
        '4 iris tomat merah',
        '1 buah alpukat, potong 2 bagian',
        'irisan bawang merah besar secukupnya',
        '2 sendok makan mayonaise',
        '2 sendok makan margarin',
      ],
      menuTools: ['Pisau', 'Wajan datar', 'Telenan', 'Sendok'],
      menuReview: '4,6',
      menuProcedure: [
        '1. Olesi kedua sisi roti gandum dengan margarin, lalu panggang dengan teflon hingga kecoklatan, sisihkan',
        '2. Ambil 1 lembar roti gandum, taruh daun selada di atasnya, lalu taruh irisan tomat, irisan bawang merah besar dan alpukat di atasnya ',
        '3. Ambil 1 lembar roti gandum yang lain, olesi satu sisinya dengan 1 sendok makan mayonaise, lalu tutup ke atas roti yang berisi sayuran di atas, ulangi untuk lembar roti gandum selanjutnya',
        '4. Potong roti yang telah diisi sayuran di atas menjadi 2 bagian, lalu sajikan.',
      ]),
  Resep(
      menuId: 26,
      menuImage: 'assets/images/foods/resep/roti2.jpg',
      menuName: 'Roti Gandum Isi Cokelat Rendah Kalori',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp24.000',
      menuPreference: 'Roti',
      menuDuration: '10 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang sedang menjalankan program diet. Kalori yang ada pada roti ini tidak lebih dari 300 kkalori.',
      menuIngredients: [
        '50 gr coklat batang (70% kakao)',
        '50 gr tepung protein tinggi',
        '50 gr tepung gandum',
        '80 ml susu almond (bisa diganti susu kedelai)',
        '3 gr ragi',
        '2 gr garam',
        '1/2 sdt garam',
        '50 ml olive oil / boleh ganti minyak goreng sepunya nya',
        '8 gr butter',
      ],
      menuTools: [
        'Pisau',
        'Wajan datar',
        'Wadah untuk Roti',
        'Panggangan',
        'Cetakan'
      ],
      menuReview: '4.4',
      menuProcedure: [
        '1. Iris coklat batang tipis tipis dan kemudian cacah, sisihkan.',
        '2. Masukan terigu, gandum, dan ragi. Aduk rata ',
        '3. Tambahkan susu sedikit demi sedikit ulen hingga rata.',
        '4. Ulen adonan sampai setengah kalis. Tambahkan garam dan butter kemudian ulen hingga kalis.',
        '5. Bulatkan adonan dan simpan di wadah yang ditutup plastik atau kain basah dalam suhu ruang selama 60 menit.',
        '6. Setelah adonan mengembang 2x lipat, kempeskan dan bagi menjadi 5 bagian kemudian dibulatkan.',
        '7. Pipihkan dengan rolling pin kemudian isi dengan coklat, lalu digulung dan tutup bagian ujung ujungnya. ',
        '8. Diamkan lagi di wadah yang ditutup plastik sampai mengembang 2x lipat.',
        '9. Panggang 20-25 menit dalam oven dengan suhu 200C. '
      ]),

  Resep(
      menuId: 27,
      menuImage: 'assets/images/foods/resep/roti3.jpg',
      menuName: 'Roti Gandum Aneka Berry Kering dan Walnut',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Roti',
      menuDuration: '13 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang ingin belajar membuat roti dari dasarnya. Roti ini terbuat asli dari gandung dan dicampur adonan berry dan wallnut yang tentunya membuat rasa semakin menggugah selera anda!',
      menuIngredients: [
        '200 gr tepung protein tinggi',
        '200 gr tepung gandum halus',
        '100 gr tepung gandum ari',
        '1 butir telur',
        '50 gr susu bubuk',
        '6 gr garam',
        '1 bungkus/11 gr ragi',
        '280 ml susu cair',
        '1 sdm gula palem',
        '60 gr gula pasir',
        '80 gr margarin, saya pake palmia',
      ],
      menuTools: [
        'Loyang kue',
        'Telenan',
        'Wadah untuk Roti',
        'Panggangan',
        'Cetakan',
        'Sutil'
      ],
      menuReview: '4.4',
      menuProcedure: [
        '1. Campur ragi dan susu cair aduk lalu ditutup dengan kain. Diamkan dan tunggu sampai berbuih.',
        '2. Campur semua bahan menjadi 1 sampai rata dan uleni sampai kalis serta tidak nempel di tangan.',
        '3. Setelah itu istirahatkan adonan selama 1 jam. Setelah 1 jam ambil adonan, gilas agar udara di dalamnya hilang.',
        '4. Beri fillingnya sesuai selera, lalu di bentuk sesuai selera juga. Selanjutnya letakkan di loyang yang sudah di oles sedikit minyak olive atau pake kertas roti, dan diamkan lagi selama 1 jam hingga mengembang lagi.',
        '5. Panggang di oven selama 30-35 menit atau sesuai cara kerja oven masing-masing dengan suhu 180 derajat celcius.',
      ]),

  Resep(
      menuId: 28,
      menuImage: 'assets/images/foods/resep/roti4.jpg',
      menuName: 'Roti Sisir Gandum',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Roti',
      menuDuration: '13 min',
      menuDescription:
          'Resep ini sangat cocok untuk anda yang ingin belajar membuat roti sisir kekinian! Anda akan dapat belajar dengan runtut bagaimana roti sisir dibuat ditambah dengan bumbu-bumbu masa kini!',
      menuIngredients: [
        '220 gr tepung protein tinggi',
        '30 gr tepung gandum',
        '20 gr creamer nabati',
        '30 gr gula pasir',
        '1/2 sdt garam',
        '170 gr air kelapa dingin kulkas kurang lebih 10C',
        '30 gr margarin',
        '4 gr instant yeast (ragi)',
        'Margarin untuk olesan',
      ],
      menuTools: [
        'Loyang kue',
        'Telenan',
        'Wadah untuk Roti',
        'Oven',
        'Cetakan'
      ],
      menuReview: '4.2',
      menuProcedure: [
        '1. Campur tepung, gula, creamer, garam dan air kelapa sampai setengah kalis, biarkan 1 jam dalam suhu ruang.',
        '2. Setelah 1 jam masukkan margarin dan yeast uleni 15 menit speed medium hingga kalis elastis.',
        '3.Lakukan windowpane test. Bila belum, tambah maksimum 5 menit tambahan.',
        '4. Adonan kalis elastis, diamkan selama 45 menit - 1 jam. Tutup dengan kain atau plastik wrap hingga double size.',
        '5. Tata di loyang, tutup dengan kain, biarkan fermentasi 45 menit-1 jam sampai double size.',
        '6. Panaskan oven 190C. Bake selama 20 menit (sesuaikan dengan oven masing-masing). Setelah matang segera oles dengan margarin selagi panas.'
      ]),

  Resep(
      menuId: 29,
      menuImage: 'assets/images/foods/resep/roti5.jpg',
      menuName: 'Kebab Roti Tawar',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp21.000',
      menuPreference: 'Roti',
      menuDuration: '9 min',
      menuDescription:
          'Resep ini akan mengajarkan kepada anda bagaimana membuat kebab yang praktis!! Anda tidak perlu jajan kebab diluar, dengan adanya resep ini anda akan dapat membuat kebab secara mandiri!',
      menuIngredients: [
        '5 lembar roti tawar',
        '2 siung bawang putih, rajang halus',
        '1 buah bawang bombay, iris tipis',
        '1 butir telur',
        '5 biji bakso (bisa diganti sosis)',
        'Bonggol jagung manis',
        '3 lembar daun selada',
        '1 sdt garam',
        '1 sdt gula',
        'Lada bubuk',
        '1 kaldu jamur',
        '2 sdm saus sambal',
        '2 sdm mayonaise',
      ],
      menuTools: [
        'Wajan',
        'Telenan',
        'Kompor',
        'Rolling pan/Botol kaca sirup',
        'Panggangan'
      ],
      menuReview: '4.2',
      menuProcedure: [
        '1. Tumis bawang putih dan bawang bombay sampai harum, masukkan telur lalu orak arik.',
        '2. Masukkan daun selada,jagung manis dan bakso (jangan diberi air).',
        '3.Tambahkan gula, garam, lada bubuk, dan kaldu jamur sesuai selera. Aduk rata. Matikan kompor.',
        '4. Iris pinggiran roti, lalu pipihkan roti menggunakan rolling pan (bisa pake botol kaca sirup).',
        '5. Isi roti dengan tumisan tadi, beri saus sambal dan mayonaise kemudian gulung rapi.',
        '6. Panggang roti di pan antilengket hingga kecokelatan (gunakan api kecil saja).',
        '7. Kebab penuh siap disajikan.'
      ]),

  Resep(
      menuId: 30,
      menuImage: 'assets/images/foods/resep/tinggiprotein0.jpg',
      menuName: 'Tumis Tempe',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp15.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '15 min',
      menuDescription:
          'Resep tumis tempe ditambah dengan rahasia dari Kukoki akan tinggi protein yang tentu membantu anda tetap sehat tanpa kandungan pengawet',
      menuIngredients: [
        '250 gram tempe potong 3 cm',
        '15 gram bawang putih iris tipis',
        '25 gram bawang merah iris tipis',
        '4 gram akar lengkuas segar (kira-kira 2 buah akar lengkuas)',
        '2 daun salam',
        '1 sdt Royco kaldu ayam',
        '2 sendok makan kecap manis bango',
        '4 sendok makan minyak goreng',
        '200 ml air'
      ],
      menuTools: ['Pisau', 'Telenan', 'Gelas ukur', 'Panci'],
      menuReview: '4,0',
      menuProcedure: [
        '1. Rebus jagung hingga air mendidih selama 5 menit',
        '2. Masukkan bawang merah, temu kunci, dan Maggi Magic Lezat. Aduk rata, masak hingga jagung matang selamat 10 menit.',
        '3. Masukkan tomat, masak sebentar hingga mendidih selama 5 menit.',
        '4. Matikan api, masukkan bayam. Angkat. ⁣ Sajikan.',
      ]),

  Resep(
      menuId: 31,
      menuImage: 'assets/images/foods/resep/tinggiprotein1.png',
      menuName: 'Sapo Tahu',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp16.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '30 min',
      menuDescription:
          'Sapo Tahu menjadi salah satu menu oriental favorit di restoran. Jadi, kenapa nggak coba bikin sendiri di rumah dengan bahan sesuai budget belanja Ibu. Nggak ada ayam? Nggak masalah, kok. Ibu cukup pakai sayuran dan jamur. Supaya rasa gurih-manisnya beda, tambahkan Saus Tiram dan perasa  Rasa Ayam. Yuk, cek resepnya di bawah!',
      menuIngredients: [
        '50 gr Jamur Kuping',
        '100 gr Jamur Merang, potong empat',
        '50 gr Jagung keputren, iris serong',
        '50 gr Wortel, iris serong',
        '100 gr brokoli, potong kuncup',
        '3 buah cabai merah, iris serong',
        '100 gr sawi putih, potong',
        '50 gr Kapri',
        '200gr  pakcoi',
        '3 gr bawang putih, cincang',
        '2 buah cabai merah, iris',
        '1/2 sdt gula pasir',
        '2 bungkus tahu putih',
        '1 sdt minyak wijen',
        '250 ml air',
        '2 sdm minyak goreng segar untuk menumis',
      ],
      menuTools: ['Pisau', 'Telenan', 'Gelas ukur', 'Sutil', 'Panci', 'wajan'],
      menuReview: '4,7',
      menuProcedure: [
        '1. Panaskan minyak, tumis bawang putih masak hingga harum dengan api kecil',
        '2. Masukkan jamur, jagung dan wortel, lalu masak hingga jamur berubah warna.',
        '3. Masukkan Maggi Saus Tiram, Maggi Magic Lezat Rasa Ayam, gula, merica, dan cabai merah. Masukkan air. Masak hingga mendidih, lalu masukkan brokoli dan kapri. Masak lagi hingga mendidih.',
        '4. Masukkan pakcoi dan sawi putih, beri larutan maizena ketika air sudah mendidih. Aduk hingga mengental',
        '5. Masukkan tofu/tahu, kemudian taburi dengan bawang daun. Sajikan.'
      ]),

  Resep(
      menuId: 32,
      menuImage: 'assets/images/foods/resep/tinggiprotein2.jpg',
      menuName: 'Kailan Cah Jamur',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp15.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '15 min',
      menuDescription:
          'Siapa bilang bikin hidangan ala resto itu susah, ? kita sudah siapkan resep makanan simple pakai perasa khas dari Kukoki. Yuk, coba bikin Kailan Cah Jamur yang praktis, bergizi, dan lezatnya pastinya beda.',
      menuIngredients: [
        '1 buah bawang bombay sedang, iris memanjang',
        '1 cm jahe, iris memanjang',
        '3 siung bawang putih, cincang',
        '2 sdm minyak goreng segar',
        '50 gr jamur merang',
        '50 gr Jamur Kuping',
        '2 sdm gula pasir',
        '1 sdt merica',
        '150ml air',
        '1 sdm tepung maizena, larutkan dengan sedikit air',
        '2 buah cabai merah, iris',
        '1/2 sdt gula pasir',
        '2 bungkus tahu putih',
        '1 sdt minyak wijen',
        '250 ml air',
        '2 sdm minyak goreng segar untuk menumis',
      ],
      menuTools: ['Pisau', 'Telenan', 'Gelas ukur', 'Sutil', 'Panci', 'wajan'],
      menuReview: '4,7',
      menuProcedure: [
        '1. Potong kailan, lalu kupas batang yang tua, rebus sebentar dalam air mendidih selama 30 detik. Angkat dan tiriskan.',
        '2. Tumis bawang bombay, jahe, dan bawang putih sampai harum.',
        '3. Masukkan jamur merang dan jamur kuping. Tambahkan Maggi Saus Tiram, gula pasir, merica, dan Maggi Magic Lezat Rasa Ayam.',
        '4. Tambahkan air, lalu masak hingga mendidih. Masukkan kailan rebus.',
        '5.  Masukkan larutan maizena, lalu masak hingga mengental. Sajikan..'
      ]),

  Resep(
      menuId: 33,
      menuImage: 'assets/images/foods/resep/tinggiprotein3.jpg',
      menuName: 'Dada Ayam Panggang',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp30.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '20 min',
      menuDescription:
          'Dada ayam dikenal akan kandungan protein yang tinggi. Dalam 100 gram dada ayam terkandung sebsar 31 gram protein. Berikut resep makanan tinggi protein dari dada ayam.',
      menuIngredients: [
        'Dada ayam tanpa tulang, besar sesuai selera',
        'Merica secukupnya',
        'Garam secukupnya',
        'Minyak zaitun atau canola',
      ],
      menuTools: ['Pisau', 'Telenan', 'Sutil', 'Panggangan', 'wajan'],
      menuReview: '4,7',
      menuProcedure: [
        '1. Tabur merica dan garam pada dada ayam, lalu baluri sampai merata.',
        '2. Panaskan teflon dengan api sedang, lalu oles sedikit dengan minyak zaitun atau canola.',
        '3. Panggang dada ayam bolak-balik sampai matang.',
        '4. Tambahkan air, lalu masak hingga mendidih. Masukkan kailan rebus.',
        '5.  Jika sudah dirasa benar-benar matang, matikan api dan diamkan di atas wajan terlebih dahulu selama 5 menit.',
        '6.  Sajikan.'
      ]),

  Resep(
      menuId: 34,
      menuImage: 'assets/images/foods/resep/tinggiprotein4.jpg',
      menuName: 'Roti Gandum Telur dan Alpukat',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '15 min',
      menuDescription:
          'Mungkin makanan ini kandungan proteinnya tidak setinggi resep makanan tinggi protein sebelumnya. Namun makanan ini sangat sehat karena kaya serat dari gandum dan juga menggunakan buah alpukat. Di dalam buah alpukat sendiri terdapat 2 gram protein tiap 100 gram.',
      menuIngredients: [
        '2 lembar roti gandum',
        '4 buah telur rebus',
        '1 sdm air lemon',
        ' 1 sdt garam',
        '1 sdm Minyak zaitun'
      ],
      menuTools: ['Pisau', 'Telenan', 'Sendok', 'Panggangan'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Panggang roti gandum hingga kering, sisihkan.',
        '2. Haluskan alpukat yang telah dipotong kecil, lalu beri garam dan air lemon.',
        '3. Masukkan telur rebus yang telah dipotong kecil, kemudian aduk rata bersama dengan alpukat.',
        '4. Susun campuran alpukat dan telur di atas roti gandum.',
        '5.  Tambahkan minyak zaitun.',
        '6.  Sajikan.'
      ]),

  Resep(
      menuId: 35,
      menuImage: 'assets/images/foods/resep/tinggiprotein5.jpg',
      menuName: 'Salad Telur dan Tomat ',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp22.000',
      menuPreference: 'Protein Tinggi',
      menuDuration: '18 min',
      menuDescription:
          'Jika Anda pecinta telur, maka salad ini sangat cocok untuk Anda. Telur adalah sumber protein yang sangat baik.',
      menuIngredients: [
        '4 tomat sedang dicincang',
        '2 bawang bombai sedang dicincang',
        '3 siung bawang putih',
        ' 4 butir telur direbus dan dicincang',
        ' 1 sendok teh (sdt) garam batu',
        ' 1 sdt lada hitam',
        ' 1 sdm minyak zaitun'
      ],
      menuTools: ['Mangkuk', 'Pisau', 'Sendok', 'Telenan'],
      menuReview: '4,2',
      menuProcedure: [
        '1. Masukkan bawang bombai, tomat, dan bawang putih ke dalam mangkuk besar.',
        '2. Setelah itu, tambahkan telur rebus, garam, lada hitam, dan minyak zaitun, lalu aduk rata.',
        '3. Jika ingin lebih gurih, Anda bisa menaburkan beberapa biji wijen panggang.',
        '4. Susun campuran alpukat dan telur di atas roti gandum.',
        '5.  Sajikan.'
      ]),

  Resep(
      menuId: 36,
      menuImage: 'assets/images/foods/resep/makananlaut0.png',
      menuName: 'Ikan Bakar Pedas',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp55.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '50 min',
      menuDescription:
          'Ikan bakar pedas sensasi ikan serasa pedas lava dimulut, rasa gurih yang bikin nagih dan terus nambah',
      menuIngredients: [
        '1 bungkus penyedap rasa ayam',
        '2 siung bawang merah, iris tipis',
        '10 buah cabai rawit, iris serong',
        '10 buah cabai keriting, iris serong',
        '1 sendok makan garam',
        "1 sendok makan minyak goreng"
      ],
      menuTools: [
        'Wajan datar',
        'Gelas ukur',
        'Panci',
        "Kompor",
        "Microwave",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,8',
      menuProcedure: [
        '1. Cuci bersih ikan buang sisik dan isi perutnya.',
        '2. Lumuri ikan dengan air jeruk nipis biarkan 15 menit kemudian cuci kembali.',
        '3. Ulek kasar bumbu, campur dengan 1 sdm minyak goreng.',
        '4. Marinasi ikan dengan bumbu selama 30 menit dalam kulkas.',
        '5. Keluarkan ikan, bakar arang dan bakar ikan sampai matang sambil dioles sisa bumbu.',
      ]),

  Resep(
      menuId: 37,
      menuImage: 'assets/images/foods/resep/makananlaut1.png',
      menuName: 'Cumi Bakar Montok',
      menuPortion: '3 Porsi',
      menuPrice: 'Rp50.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '40 min',
      menuDescription:
          'Cumi Bakar Montok sensasi manis, asem, dan gurih, rasa gurih yang bikin nagih dan terus nambah',
      menuIngredients: [
        '1 buah cumi seberat 600gr',
        '1 sendok makan asam jawa',
        '1 gelas air',
        '3 udang kupas seberat 150 gr',
        '1 batang daun bawang kecil',
        "1 butir telur ayam",
        "2 sendok makan minyak goreng",
        "Garam secukupnya",
        'Garam secukupnya',
        "1 botol saus grill master hot dan crispy barbeque",
        "1 bungkus grill master seafood magic rub",
        "Garlic powder secukupnya",
        "Chilli Flakes secukupnya",
        "Basil Leaves secukupnya",
      ],
      menuTools: [
        'Gelas ukur',
        'Panci',
        "Kompor",
        "Microwave",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,9',
      menuProcedure: [
        '1. Cuci bersih cumi, keluarkan telurnya, tiriskan badan dan kepalanya.',
        '2. Cincang kasar telur cumi dan udang, tuang dalam wadah.',
        '3. Tambahkan telur ayam yang sudah dikocok, daun bawang iris, garlic powder, garam, lada bubuk dan sedikit basil leaves.',
        '4. Lalu masukan ke dalam perut cumi, semat dengan lidi.',
        '5. Remas-remas asam jawa dengan air, buang ampasnya, tambahkan 1/2 pax grill master hot dan spicy barbeque, satu sendok makan grill master seafood magic rub, secukupnya chili flakes dan gula pasir.',
        "6. Aduk rata lalu marinade cumi beserta kepalanya kurang lebih 30 menit.",
        "7. Panaskan teflon, oles dengan minyak goreng, bakar cumi sambil dibolak balik dan diolesi bumbu marinade tadi."
            "8. Bakar sampai matang, angkat, potong-potong dan siap disajikan"
      ]),

  Resep(
      menuId: 38,
      menuImage: 'assets/images/foods/resep/makananlaut2.png',
      menuName: 'Kerang Hijau Saus Padang Pedas',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp35.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '30 min',
      menuDescription:
          'Kerang Hijau dimasak dengan saus khas Padang autentik. Rasa manisnya mampu bikin lidah anda bergoyang',
      menuIngredients: [
        '1 buah bawang bombai, diiris panjang',
        '1 sendok makan saus tiram',
        '3 sendok makan saus tomat',
        '4 sendok makan saus sambal',
        '1 botol air seberat 200 ml',
        "2 sendok makan margarin untuk menumis",
        "Garam, merica dan gula pasir secukupnya",
        "1 butir telur untuk mengentalkan",
        "3 buah cabai rawit",
        "3 buah cabai merah keriting",
      ],
      menuTools: [
        "Microwave",
        'Wajan Lonjong',
        'Sendok',
        'Panci',
        "Kompor",
        "Blender",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,3',
      menuProcedure: [
        '1. Rebus kerang dalam air bersama daun salam sampai mendidih. Saring dan buang airnya. Pastikan tidak sampai kerang over cook, setelah dingin cabut serabut kerang agar bersih.',
        '2. Panaskan margarine, tumis bawang bombai, cabai rawit, dan bumbu halus sampai harum.',
        '3. Masukkan saus tiram, saus tomat, saus sambal, garam, merica bubuk, dan gula. Aduk rata. Tuang air. Masak sampai mendidih.',
        '4. Masukkan kerang, aduk rata.',
        '5. Masak sampai matang, Kentalkan dengan telur aduk rata.',
        '5. Masak sampai meletup-letup.',
        '5. Angkat dan sajikan.',
      ]),

  Resep(
      menuId: 39,
      menuImage: 'assets/images/foods/resep/makananlaut3.png',
      menuName: 'Tumis Kerang Dara pedas',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp30.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '20 min',
      menuDescription:
          'Kerang Dara ditumis dan dimasak dengan saus khas Manado. Rasa pedas dan manisnya mampu bikin bibir anda gonjor karena pedasnya',
      menuIngredients: [
        '1 lusin kerang dara rebus seberat 200 gram',
        '1 batang daun bawang, iris',
        '1 buah tomat, iris',
        '1 sendok teh garam',
        '1/2 sendok teh gula pasir',
        "13 buah cabai rawit, iris",
        "1 gelas air seberat 150 ml",
        "3 sendok makan saus tiram",
        "5 siung bawang putih, iris tipis",
        "7 siung bawang merah, iris tipis",
      ],
      menuTools: [
        'Wajan Lonjong',
        'Panci',
        'Sendok',
        "Blender",
        "Kompor",
        "Spatula",
        "Ulekan",
        "Pisau"
      ],
      menuReview: '4,5',
      menuProcedure: [
        '1. Panaskan sedikit minyak. Masukkan bawang merah, bawang putih, cabai, dan tomat. Tumis sampai harum.',
        '2. Masukkan kerang. Tambahkan air, gula, dan garam. Aduk rata.',
        '3. Tambahkan saus tiram dan daun bawang. Masak sampai bumbu meresap. Angkat dan sajikan.',
      ]),

  Resep(
      menuId: 40,
      menuImage: 'assets/images/foods/resep/makananlaut4.png',
      menuName: 'Asam Padeh Ikan',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp60.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '50 min',
      menuDescription:
          'Asam Padeh Ikan ditumis dan dimasak dengan saus khas Sumatera. Dengan rasa gurih dan pedas yang nampol dan bikin tubuh hangat',
      menuIngredients: [
        '2 ekor ikan salem',
        '3 buah tomat merah iris',
        '2 buah asam kandis',
        '1 batang serai geprek',
        '2 lembar daun salam',
        "3 lembar daun jeruk",
      ],
      menuTools: [
        'Panci',
        'Sendok',
        "Blender",
        "Pisau",
        "Spatula",
        "Ulekan",
        "Kompor",
        'Wajan Lonjong',
      ],
      menuReview: '4,4',
      menuProcedure: [
        '1. Masukkan dalam wajan bumbu halus, daun jeruk, salam, sere tambahkan air secukupnya lalu didihkan.',
        '2. Setelah mendidih masukkan ikan, asam kandis, beri garam secukupnya.',
        '3. Masak sampai kuah menyusut dan mengental.',
        "4. Terakhir koreksi rasa tambahkan irisan tomat dan sajikan."
      ]),

  Resep(
      menuId: 41,
      menuImage: 'assets/images/foods/resep/makananlaut5.png',
      menuName: 'Rajungan Saus Pedas',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp80.000',
      menuPreference: 'Makanan Laut',
      menuDuration: '60 min',
      menuDescription:
          'Rajungan saus pedas ditumis dan dimasak dengan saus khas Bandung. Dengan rasa gurih dan pedas yang nampol',
      menuIngredients: [
        '4 ekor rajungan',
        '1 buah bawang bombai, iris memanjang',
        '2 butir telur ukuran kecil, kocok lepas',
        '1 sendok makan kecap ikan',
        '1 sendok teh kecap manis',
        "1 sendok makan pasta cabai",
        "2 sendok makan saus sambal",
        "1 sendok makan saus tomat",
        "1/2 sendok teh merica bubuk",
        "100 ml air rebusan rajungan",
        "1 sendok teh perasan jeruk nipis",
        "Garam secukupnya",
        "5 siung bawang putih",
        "1 ruas jari jahe",
        "4 buah cabai merah besar"
      ],
      menuTools: [
        "Pisau",
        'Panci',
        "Kompor",
        'Sendok',
        "Blender",
        'Wajan Lonjong',
        "Spatula",
        "Ulekan",
      ],
      menuReview: '4,7',
      menuProcedure: [
        '1. Bersihkan kotoran rajungan dengan air mengalir.',
        '2. Didihkan air, kemudian masukkan rajungan, masak hingga matang (berubah warna menjadi merah), kemudian angkat dan tiriskan.',
        '3. Memarkan capit rajungan, cungkil cangkangnya agar bumbu bisa meresap nanti.',
        "4. Tumis bawang bombai hingga transparan, masukkan bumbu halus, saus sambal, saus tomat, merica, minyak ikan dan kecap manis, tumis hingga harum, masukkan air rebusan rajungan.",
        "5. Masukkan rajungan, kemudian masukkan kocokan telur agar bumbu mengental, masak dengan api kecil beberapa menit hingga bumbu meresap ke rajungan.",
        "6. Matikan api, lalu masukkan air jeruk nipis."
      ]),
  Resep(
      menuId: 42,
      menuImage: 'assets/images/foods/resep/menudiet0.png',
      menuName: 'Sayur Bayam Kecambah',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Menu Diet',
      menuDuration: '15 min',
      menuDescription:
          'Sayur Bayam Kecambah menu andalanmu ketika anda ingin mencari gaya hidup sehat yang baru. Sayur bayam kecamah manis direbus dan ditumis dengan bumbu khas Manado.',
      menuIngredients: [
        '1/2 ikat bayam',
        'sejumput kecambah',
        'bawang merah secukupnya',
        'bawang putih secukupnya',
        'cabai secukupnya',
        '1 sendok teh garam',
        '1/2 sendok teh minyak zaitun untuk menumis',
      ],
      menuTools: [
        "Spatula",
        "Ulekan",
        'Pisau',
        'Wajan datar',
        'Gelas ukur',
        'Panci'
      ],
      menuReview: '4,7',
      menuProcedure: [
        '1. Tumis bawang dan cabai.',
        '2. Masukkan daun bayam, masak sampai layu.',
        '3. Tambahkan kecambah. Beri sedikit garam. Dan siap disajikan.',
      ]),

  Resep(
      menuId: 43,
      menuImage: 'assets/images/foods/resep/menudiet1.png',
      menuName: 'Ayam Pedas Manis',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp34.000',
      menuPreference: 'Menu Diet',
      menuDuration: '35 min',
      menuDescription:
          'Ayam Pedas Manus paduan ayam cincang dengan saus pedas khas Surabaya. Rasa asin dan gurih yang nampol dan nagih.',
      menuIngredients: [
        '1 ayam dada fillet seberat 100 gram',
        '1 siung bawang putih cincang',
        'daun bawang, ambil bagian putihnya secukupnya',
        'perasan lemon',
        '1 buah tomat potong dadu',
        '1/2 sendok teh garam',
        '1 sendok makan pasta tomat',
        "1 sendok makan kecap manis"
      ],
      menuTools: [
        "Ulekan",
        "Spatula",
        'Gelas ukur',
        'Wajan datar',
        'Pisau',
        'Panci'
      ],
      menuReview: '4,9',
      menuProcedure: [
        '1. Rendam ayam dengan semua bumbu kecuali tomat selama 10 menit.',
        '2. Panaskan pan, masukkan rendaman ayam.',
        '3. Beri sedikit air, masak hingga matang.',
        "4. Masukkan tomat, masak sebentar. Dan siap disajikan."
      ]),

  Resep(
      menuId: 44,
      menuImage: 'assets/images/foods/resep/menudiet2.png',
      menuName: 'Ramen Diet',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp36.000',
      menuPreference: 'Menu Diet',
      menuDuration: '45 min',
      menuDescription:
          'Ramen yang dibuat khusus untuk orang yang ingin menurunkan berat badan. Rasanya tidak kalah dengan paduan kalori hanya 350 kalori per porsi.',
      menuIngredients: [
        ' 3 cm jahe iris kecil2',
        '6 bawang merah',
        "1 fillet dada ayam seberat 200 gram"
            '4 bawang putih',
        '5 cabai rawit kecil',
        '2-4 sendok makan kecap asin',
        '1/2 sendok teh garam',
        '1 sendok teh gula pasir',
        "1 sendok teh penyedap",
        "1500 ml air",
        "2 sendok makan fiber cream",
        "1 bakul sawi",
        "mie seberat 300 gram",
        "2 wortel",
        "2 jagung manus kuning",
        "2 butir telur rebus"
      ],
      menuTools: [
        "Sodet",
        'Gelas ukur',
        "Spatula",
        'Wajan datar',
        "Ulekan",
        'Panci',
        'Pisau'
      ],
      menuReview: '4,5',
      menuProcedure: [
        '1. Rebus air, masukkan dada ayam dan beri kecap asin.',
        '2. Cacah bawang merah, bawang putih, dan cabai. Masukkan ke rebusan ayam.',
        '3. Masukkan jahe, garam, gula pasir, dan penyedap. Masak kurang lebih 20 menit.',
        "4. Tiriskan potongan ayam. Saring airnya, ambil bawang dan cabai lalu blender.",
        "5. Masak lagi air kuahnya. Tambahkan bawang dan cabai blender.",
        "6. Tuang fiber cream, aduk, dan hidangan siap disajikan."
      ]),

  Resep(
      menuId: 45,
      menuImage: 'assets/images/foods/resep/menudiet3.png',
      menuName: 'Cream Soup',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp32.000',
      menuPreference: 'Menu Diet',
      menuDuration: '25 min',
      menuDescription:
          'Cream soup sederhana dengan perpaduan kuah yang creamy dan campuran sayur yang renyah, manis, dan sehat.',
      menuIngredients: [
        '200 gram ayam fillet',
        '1 buah wortel, potong dadu kecil',
        "2 siung bawang putih dicincang halus"
            '300 ml susu cair',
        '400 ml air',
        '1/2 bawang bombay, potong dadu',
        '4 buah bakso, potong dadu',
        '4 sdm tepung terigu + 100 ml air',
        "1 sdt lada bubuk",
        "garam secukupnya",
        "minyak goreng secukupnya",
        "2 roti tawar panggang",
      ],
      menuTools: [
        "Spatula",
        "Sendok",
        "Sodet",
        "Ulekan",
        'Gelas ukur',
        'Wajan datar',
        'Pisau',
        'Panci'
      ],
      menuReview: '4,5',
      menuProcedure: [
        '1. Rebus ayam sampai empuk, angkat dan tiriskan. Potong sesuai selera.',
        '2. Rebus wortel sampai empuk di kuah ayam.',
        '3. Tumis bawang putih dan bawang bombay. Masukkan susu cair, garam, dan lada. Masak sampai mendidih.',
        "4. Campur ke dalam panci kuah rebusan ayam, masukkan lagi ayam. Beri bakso, aduk rata.",
        "5. Tambahkan campuran terigu, masak sampai agak kental. Dan siap disajikan",
      ]),

  Resep(
      menuId: 46,
      menuImage: 'assets/images/foods/resep/menudiet4.png',
      menuName: 'Steak Tempe',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp20.000',
      menuPreference: 'Menu Diet',
      menuDuration: '15 min',
      menuDescription:
          'Steak Tempe, menu inovasi baru yang menggabungkan tempe panggang yang amat gurih dengan campuran aneka sayur dan bumbu barbeque yang lezat dan manis.',
      menuIngredients: [
        '1/2 papan tempe',
        '2 sendok makan tepung gluten free',
        "1/2 sendok teh lada putih"
            'himsalt secukupnya',
        'minyak kelapa',
        '6 siung bawang putih, potong kecil',
        '1/2 siung bombay, iris sesuai selera',
        '2 buah tomat, haluskan',
        "kecap manis organic secukupnya",
        "lada hitam utuh, ulek kasar",
        "gula aren sesuai selera",
        "1 sendok makan minyak kelapa",
        "air secukupnya"
      ],
      menuTools: [
        "Sendok",
        "Sodet",
        "Ulekan",
        'Gelas ukur',
        'Wajan datar',
        'Pisau'
      ],
      menuReview: '4,8',
      menuProcedure: [
        '1. Kukus tempe sampai matang. Kemudian haluskan.',
        '2. Campur tempe dengan tepung, lada putih, dan garam.',
        '3. Bentuk sesuai selera, masak dengan api kecil hingga matang. Angkat dan sisihkan.',
        "4. Saus: tumis bawang putih sampai harum. Masukkan bawang bombay, aduk sampai layu.",
        "5. Masukkan semua bahan lain kecuali garam. Masak sampai mendidih.",
        "6. Matikan api, beri garam lalu aduk rata.",
        "7. Tuang saus ke steak tempe.Dan siap disajikan."
      ]),

  Resep(
      menuId: 47,
      menuImage: 'assets/images/foods/resep/menudiet5.png',
      menuName: 'Salad Caesar',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp38.000',
      menuPreference: 'Menu Diet',
      menuDuration: '25 min',
      menuDescription:
          'Salad Caesar sehat perpaduan sayur segar dan manis dengan saus caesar yang cenderung manis dan gurih.',
      menuIngredients: [
        '100-120 gram selada romaine',
        '20-40 gram telur rebus',
        "60 gram keju parmesan"
            '15-20 gram daging sapi iris tipis',
        '20-25 roti tawar, potong dadu lalu panggang',
        'lada secukupnya',
        'garam secukupnya',
        'saus salad kemasan',
      ],
      menuTools: ["Sendok", "Sodet", 'Mangkok Aduk', 'Pisau', "Gunting"],
      menuReview: '4,9',
      menuProcedure: [
        '1. Potong selada romaine sesuai selera.',
        '2. Goreng daging sapi dengan sedikit olive oil. Beri sedikit bumbu sesuai selera.',
        '3. Potong roti tawar menjadi dadu. Beri bumbu seperti garam dan lada, lalu panggang.',
        "4. Masukan bahan-bahan yang sudah jadi ke dalam satu mangkuk, lalu tuangkan saus. Aduk rata dan sajikan.",
      ]),
  Resep(
      menuId: 48,
      menuImage: 'assets/images/foods/imagefood2.png',
      menuName: 'Unagi Ramen',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp30.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '30 min',
      menuDescription:
      'Ramen khas Jepang dengan tambahan Unagi atau belut yang manis dan gurih.',
      menuIngredients: [
        '100 ml mirin',
        '4 sdm kecap',
        '30 gram gula pasir',
        'lada secukupnya',
        'garam secukupnya',
      ],
      menuTools: ["Sendok", "Oven", 'Mangkok Aduk', 'Pisau', "Gunting", "Panci"],
      menuReview: '4,9',
      menuProcedure: [
        '1. Keluarkan unagi frozen terlebih dahulu supaya mencapai suhu ruangan, dan campur bahan saus hingga menjadi satu.',
        '2. Panggang unagi dalam oven selama 8 sampai 10 menit di suhu 210 C.',
        '3. Setelah 8 sampai 10 menit keluarkan unagi. Lalu olesi dengan saus hingga merata. Dan lanjutkan memanggang dengan oven suhu maksimal selama 2 sampai 3 menit.',
        "4. Rebus mie ramen selama 15 menit.",
        "5. Sajikan ramen dengan unagi yang telah dipanggang.",
      ]),

  Resep(
      menuId: 49,
      menuImage: 'assets/images/foods/imagefood3.png',
      menuName: 'Nabe Veggie Udon',
      menuPortion: '2 Porsi',
      menuPrice: 'Rp25.000',
      menuPreference: 'Sayur',
      menuDuration: '30 min',
      menuDescription:
      'Ramen khas Jepang dengan sayuran-sayuran sehat tanpa daging.',
      menuIngredients: [
        '1 bungkus udon',
        '4 gram jamur kuping',
        '4 gram jamur enoki',
        '1/2 sdt lada putih bubuk',
        '1 sdm minyak wijen',
        '1/2 sdt kaldu jamur',
        '2 siung bawang putih',
        '300 ml air ',
        'lada secukupnya',
        'garam secukupnya',
      ],
      menuTools: ["Sendok", "Oven", 'Mangkok', 'Pisau', "Gunting", "Panci"],
      menuReview: '4,9',
      menuProcedure: [
        '1. Potong-potong sayur dan jamur menjadi bagian kecil-kecil.',
        '2. Keluarkan udon dan rebus selama 15 menit di panci.',
        '3. Masukkan sayur dan jamur ke dalam panci.',
        '4. Aduk panci selama 15 menit.',
        '5. Sajikan ramen di mangkok.',
      ]),

  Resep(
      menuId: 50,
      menuImage: 'assets/images/foods/imagefood5.png',
      menuName: 'Pesto Pasta Chicken',
      menuPortion: '2 Porsi',
      menuPrice: '30.000',
      menuPreference: 'Daging dan Sayur',
      menuDuration: '30 min',
      menuDescription:
      'Pasta Pesto Khas Italia dengan Ayam Panggang',
      menuIngredients: [
        '225 gram spaghetti',
        '50 gram pine nuts / Almond',
        '50 gram keju parmesan',
        '2 siung bawang putih',
        '100 ml minyak zaitun ',
        '1 sdm air',
        '1/2 dada ayam',
        'lada secukupnya',
        'garam secukupnya',
      ],
      menuTools: ["Sendok", "Oven", 'Mangkok', 'Pisau', "Gunting", "Panci"],
      menuReview: '4,9',
      menuProcedure: [
        '1. Siapkan panci, isi air agak banyak dan 1/2 sendok makan garam. Rebus hingga mendidih. Masukkan pasta, rebus hingga matang al dente. Angkat, tiriskan, sisihkan sekitar 1/2 gelas air rebusan pasta. Sisihkan.',
        '2. Panaskan 1 sendok makan minyak di wajan, tumis bawang putih dan bawang bombay hingga matang, layu dan terlihat karamel. Masukkan ayam, garam, merica, tumis hingga ayam matang dan berubah warna menjadi agak kecoklatan. Angkat.',
        '3. Tuangkan pasta rebus ke tumisan ayam, tambahkan pesto. Aduk rata. Jika terlalu pekat, tambahkan sedikit air rebusan pasta yang tadi disisihkan. Cicipi rasanya, sesuaikan asinnya, sajikan.  Yummy!',
      ]),
];
